/* tslint:disable object-literal-sort-keys*/

// import type { ActionTypes } from '../flowTypes/Actions'
export const actionTypes: any = {
	// PAGINATION
	REQUEST_PAGE: 'REQUEST_PAGE',
	RECEIVE_PAGE: 'RECEIVE_PAGE',

	// BREAKPOINT
	CHANGE_BREAKPOINT: 'CHANGE_BREAKPOINT',

	// MODAL
	SHOW_MODAL: 'SHOW_MODAL',
	HIDE_MODAL: 'HIDE_MODAL',

	// Loading Bar
	SHOW_LOADING_BAR: 'SHOW_LOADING_BAR',
	HIDE_LOADING_BAR: 'HIDE_LOADING_BAR',

	// Products
	LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
	LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
	ADD_TO_CART: 'ADD_TO_CART',
	UPDATE_CART_TOTAL: 'UPDATE_CART_TOTAL',
	UPDATE_CART_STATE: 'UPDATE_CART_STATE'

}
